### ISSUE TITLE
Dates showing as 2944

### ISSUE THREAD

**Issue by noelhunter** [teverett/paradoxReader#6]
In my export, all of the dates are showing as 2944.  

The paradox field definition is:

[MyDate] => Array
        (
            [type] => 2
            [size] => 4
        )

In my CSV, all dates end up as 2944.  Any ideas if this is a bug, or is I am doing something wrong?

**Comment by noelhunter** [comment]
I have tested, and if I modify the file:

/src/main/java/com/khubla/pdxreader/db/DBTableValue.java

to return type D the same as is used for type I, with:

`case D:
                  data[0] = (byte) (data[0] & 0x7f); // handle unsigned integers
                  final long d = ByteBuffer.wrap(data).order(ByteOrder.BIG_ENDIAN).getInt();
                  value = Long.toString(d);
                  break;`

my CSV contains raw data such as: 737412, for days Since Year 0 (December 19, 2018) offset by a year.  I can use that for my purposes, and leave for others to improve.

I can use this raw data for my import.

**Comment by teverett** [comment]
@noelhunter  thanks!  Would you be able to submit a PR?

**Comment by teverett** [comment]
Fixed in commit 
b9e0eed
